// Generated by CoffeeScript 1.9.0
(function() {
  var IPManager, StormData, StormRegistry, async, extend, ip, iplist, request, subnetting, util;

  StormRegistry = require('stormregistry');

  StormData = require('stormdata');

  util = require('util');

  request = require('request-json');

  extend = require('util')._extend;

  ip = require('ip');

  async = require('async');

  subnetting = function(net, curprefix, newprefix) {
    var answer, iter, iterations, netmask, newmask, xx;
    netmask = ip.fromPrefixLen(curprefix);
    newmask = ip.fromPrefixLen(newprefix);
    xx = new Buffer(4);
    iter = newprefix - curprefix;
    iterations = Math.pow(2, iter);
    answer = [];
    (function() {
      var i, result, str, _i, _j, _ref, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref = iterations - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        result = ip.subnet(net, newmask);
        result.status = "free";
        result.iparray = [];
        xx = ip.toBuffer(result.firstAddress);
        for (i = _j = 0, _ref1 = result.numHosts - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          result.iparray[i] = ip.toString(xx);
          xx[3]++;
        }
        answer.push(result);
        xx = ip.toBuffer(result.broadcastAddress);
        xx[3]++;
        if (xx[3] === 0x00) {
          xx[2]++;
        }
        str = ip.toString(xx);
        _results.push(net = str);
      }
      return _results;
    })();
    return answer;
  };

  iplist = function(address) {
    var i, iparray, result, xx, _i, _ref;
    iparray = [];
    result = ip.subnet(address, '255.255.255.0');
    xx = ip.toBuffer(result.firstAddress);
    for (i = _i = 0, _ref = result.numHosts - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      iparray[i] = ip.toString(xx);
      xx[3]++;
    }
    return iparray;
  };

  IPManager = (function() {
    function IPManager(wan, lan, mgmt) {
      util.log("wan pool " + wan + " ");
      util.log("lan pool " + lan + " ");
      util.log("mgmt pool " + mgmt);
      this.wansubnets = subnetting(wan, 24, 30);
      this.lansubnets = subnetting(lan, 24, 27);
      this.wanindex = 0;
      this.lanindex = 0;
      this.mgmtindex = 1;
      this.mgmtips = iplist(mgmt);
    }

    IPManager.prototype.listwansubnets = function() {
      return util.log("wansubnets " + JSON.stringify(this.wansubnets));
    };

    IPManager.prototype.listlanubnets = function() {
      return util.log("lansubnets " + JSON.stringify(this.lansubnets));
    };

    IPManager.prototype.getFreeWanSubnet = function() {
      return this.wansubnets[this.wanindex++];
    };

    IPManager.prototype.getFreeLanSubnet = function() {
      return this.lansubnets[this.lanindex++];
    };

    IPManager.prototype.getFreeMgmtIP = function() {
      return this.mgmtips[this.mgmtindex++];
    };

    return IPManager;

  })();

  module.exports = IPManager;

}).call(this);
