// Generated by CoffeeScript 1.7.1
(function() {
  var StormData, StormRegistry, async, extend, ip, request, switches, util, vnetbuilderurl, vnetprovisionerurl;

  StormRegistry = require('stormregistry');

  StormData = require('stormdata');

  util = require('util');

  request = require('request-json');

  extend = require('util')._extend;

  ip = require('ip');

  async = require('async');

  vnetbuilderurl = 'http://localhost:5680/';

  vnetprovisionerurl = 'http://localhost:5681/';

  switches = (function() {
    function switches(sw) {
      this.config = extend({}, sw);
      this.status = {};
      this.statistics = {};
      util.log(" switch config " + JSON.stringify(this.config));
    }

    switches.prototype.create = function(callback) {
      var client;
      client = request.newClient('http://localhost:5680/');
      return client.post('/switch', this.config, (function(_this) {
        return function(err, res, body) {
          if (err != null) {
            util.log("err" + JSON.stringify(err));
          }
          util.log("create switches result " + JSON.stringify(body));
          _this.uuid = body.id;
          _this.status.result = body.status;
          if (body.reason != null) {
            _this.status.reason = body.reason;
          }
          return callback;
        };
      })(this));
    };

    switches.prototype.del = function(callback) {
      var client;
      client = request.newClient('http://localhost:5680/');
      return client.del("/switch/" + this.uuid, (function(_this) {
        return function(err, res, body) {
          if (err != null) {
            util.log("err" + JSON.stringify(err));
          }
          util.log("delete switches result " + JSON.stringify(body));
          if (!(body instanceof Error)) {
            _this.status.result = body.status;
            return _this.status.reason = body.reason(body.reason != null ? callback(_this.result) : void 0);
          }
        };
      })(this));
    };

    switches.prototype.get = function() {
      return {
        "uuid": this.uuid,
        "config": this.config,
        "status": this.status,
        "statistics": this.statistics
      };
    };

    switches.prototype.stop = function() {};

    switches.prototype.start = function() {};

    switches.prototype.switchStatus = function() {};

    switches.prototype.statistics = function() {};

    return switches;

  })();

  module.exports = switches;

}).call(this);
